# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "page_manager"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthias Folz"]
  s.date = "2011-11-23"
  s.description = "TODO: longer description of your gem"
  s.email = "folz.matthias@googlemail.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rvmrc",
    "Capfile",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "README",
    "Rakefile",
    "VERSION",
    "app/admin/dashboards.rb",
    "app/admin/nodes.rb",
    "app/admin/pages.rb",
    "app/assets/.sass-cache/0cccc8f8f88e6da0ee49b42420d3732420522c9f/buttons.scssc",
    "app/assets/.sass-cache/0cccc8f8f88e6da0ee49b42420d3732420522c9f/ie.scssc",
    "app/assets/.sass-cache/0cccc8f8f88e6da0ee49b42420d3732420522c9f/print.scssc",
    "app/assets/.sass-cache/0cccc8f8f88e6da0ee49b42420d3732420522c9f/screen.scssc",
    "app/assets/.sass-cache/188be3e3143469cbf426948260ad05c1d826db72/_support.scssc",
    "app/assets/.sass-cache/3bb5c04fe20086b066b961ec72ddea846ed0814a/_grid-background.scssc",
    "app/assets/.sass-cache/4b340630174f543aee08058b2ba7d71d965fe258/_blueprint.scssc",
    "app/assets/.sass-cache/4e2c6b40fb9d4c8db3d259aa5722ea2eaf7ffc7b/_base.scssc",
    "app/assets/.sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_clearfix.scssc",
    "app/assets/.sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_float.scssc",
    "app/assets/.sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_hacks.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_buttons.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_colors.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_debug.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_form.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_grid.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_ie.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_interaction.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_print.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_reset.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_scaffolding.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_typography.scssc",
    "app/assets/.sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_utilities.scssc",
    "app/assets/.sass-cache/a753e4e2ac7be99864eb2c1c8892da1f137e3440/_nowrap.scssc",
    "app/assets/.sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_background-size.scssc",
    "app/assets/.sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_images.scssc",
    "app/assets/.sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_inline-block.scssc",
    "app/assets/.sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_shared.scssc",
    "app/assets/.sass-cache/cd8a54404b95ecc66a330284acf22676a8113ef5/_link-colors.scssc",
    "app/assets/.sass-cache/fe9cdc05e28d46e546d80709e57a9292bb29c19c/_utilities.scssc",
    "app/assets/config.rb",
    "app/assets/images/buttons/cross.png",
    "app/assets/images/buttons/key.png",
    "app/assets/images/buttons/tick.png",
    "app/assets/images/grid.png",
    "app/assets/images/rails.png",
    "app/assets/javascripts/active_admin.js",
    "app/assets/javascripts/application.js",
    "app/assets/sass/buttons.scss",
    "app/assets/sass/ie.scss",
    "app/assets/sass/partials/_base.scss",
    "app/assets/sass/print.scss",
    "app/assets/sass/screen.scss",
    "app/assets/stylesheets/active_admin.css.scss",
    "app/assets/stylesheets/application.css",
    "app/assets/stylesheets/buttons.css",
    "app/assets/stylesheets/ie.css",
    "app/assets/stylesheets/print.css",
    "app/assets/stylesheets/screen.css",
    "app/controllers/application_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/tour_data_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/tour_data_helper.rb",
    "app/mailers/.gitkeep",
    "app/models/.gitkeep",
    "app/models/admin_user.rb",
    "app/models/node.rb",
    "app/models/page.rb",
    "app/models/tour_datum.rb",
    "app/views/layouts/application.html.erb",
    "app/views/layouts/intro.html.erb",
    "app/views/layouts/templates/footer.html.erb",
    "app/views/layouts/templates/navigation.html.erb",
    "app/views/pages/news.html.erb",
    "app/views/pages/show.html.erb",
    "app/views/pages/start.html.erb",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/deploy.rb",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/active_admin.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/devise.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/sass.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/initializers/wrap_parameters.rb",
    "config/locales/de.yml",
    "config/locales/devise.en.yml",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/migrate/20111012185415_create_pages.rb",
    "db/migrate/20111012190025_create_nodes.rb",
    "db/migrate/20111012191238_devise_create_admin_users.rb",
    "db/migrate/20111012211246_create_admin_notes.rb",
    "db/migrate/20111012211247_move_admin_notes_to_comments.rb",
    "db/schema.rb",
    "db/seeds.rb",
    "doc/README_FOR_APP",
    "lib/assets/.gitkeep",
    "lib/tasks/.gitkeep",
    "lib/tasks/devise.rake",
    "log/.gitkeep",
    "log/development.log",
    "log/production.log",
    "log/test.log",
    "public/404.html",
    "public/422.html",
    "public/500.html",
    "public/favicon.ico",
    "public/robots.txt",
    "public/stylesheets/active_admin.css.css",
    "public/stylesheets/tour_data.css.css",
    "script/rails",
    "test/fixtures/admin_users.yml",
    "test/functional/.gitkeep",
    "test/integration/.gitkeep",
    "test/performance/browsing_test.rb",
    "test/test_helper.rb",
    "test/unit/.gitkeep",
    "test/unit/admin_user_test.rb",
    "test/unit/node_test.rb",
    "test/unit/page_test.rb",
    "tmp/cache/assets/C55/270/sprockets%2F9fc621002859319164c4ad3d461f8837",
    "tmp/cache/assets/C55/6B0/sprockets%2F73dc278c30d7612c050645895d4b4279",
    "tmp/cache/assets/C7E/CF0/sprockets%2F3b47a33566d7031369961db4426c7a2f",
    "tmp/cache/assets/CC9/380/sprockets%2Ffb75a047999b44655a989f44f85cb070",
    "tmp/cache/assets/CEC/1A0/sprockets%2F87fdead6014b961bb870b5931890d677",
    "tmp/cache/assets/CF7/1B0/sprockets%2Fd3a08efec6519012430542b9cb0190ac",
    "tmp/cache/assets/D09/980/sprockets%2F442fa63109403cf35f5818ac29acb5e6",
    "tmp/cache/assets/D0B/C40/sprockets%2F2e9f2d904391c4506d7b46adc606c42c",
    "tmp/cache/assets/D15/F40/sprockets%2F83d1a8006e470e79f75592d63bdedc04",
    "tmp/cache/assets/D32/A10/sprockets%2F13fe41fee1fe35b49d145bcc06610705",
    "tmp/cache/assets/D37/2C0/sprockets%2Fea5b983a90517c04dab628dcb27414f4",
    "tmp/cache/assets/D38/540/sprockets%2F86e1ad844bc9df4491a2a52b870421db",
    "tmp/cache/assets/D3A/900/sprockets%2Fb7cb7a4cf2cb085e70268693ec2351d2",
    "tmp/cache/assets/D4C/880/sprockets%2F7a7c0bf1897981609e7aef03f5a06ae9",
    "tmp/cache/assets/D54/ED0/sprockets%2F71c9fa01091d432b131da3bb73faf3d4",
    "tmp/cache/assets/D65/B90/sprockets%2F4a15692136048dcd4c118eddcc723fae",
    "tmp/cache/assets/D84/210/sprockets%2Fabd0103ccec2b428ac62c94e4c40b384",
    "tmp/cache/assets/D8E/1B0/sprockets%2Fd10c5bc9d5df00b203dc3f308dca5678",
    "tmp/cache/assets/D9E/430/sprockets%2Fc5bc6691a81f9d81ac9ed6c258c14ba0",
    "tmp/cache/assets/D9E/670/sprockets%2F95b4a09faf3ebd64b75a30857d48cad1",
    "tmp/cache/assets/DA8/350/sprockets%2F10648fcfe24d86bfc33c895aa9ca25e8",
    "tmp/cache/assets/DC1/220/sprockets%2Fd1dfafd757bb02e39ae0249b2e1137eb",
    "tmp/cache/assets/DCF/A60/sprockets%2F8fe0091aca32a97b2e8f69a0193dffdc",
    "tmp/cache/assets/DD1/AA0/sprockets%2Faf978f0bc54c22ce3c333bf766ddf06e",
    "tmp/cache/assets/DD5/CD0/sprockets%2F4e9cde1bd27a0dcbd6059f9939b952ba",
    "tmp/cache/assets/DD7/570/sprockets%2F144dee2a4e95d0de8d88d35c8dbdd480",
    "tmp/cache/assets/DDE/420/sprockets%2Ffb8b186d5bf0307f86f65fc787d2adeb",
    "tmp/cache/assets/E04/890/sprockets%2F2f5173deea6c795b8fdde723bb4b63af",
    "tmp/cache/sass/188be3e3143469cbf426948260ad05c1d826db72/_support.scssc",
    "tmp/cache/sass/1b3ee43c2ed9fa90325cd7c8c700532680aa8ea3/_base.scssc",
    "tmp/cache/sass/2498a587ac2ba03461be3ee8400e5f6f322397d7/ie.scssc",
    "tmp/cache/sass/2498a587ac2ba03461be3ee8400e5f6f322397d7/print.scssc",
    "tmp/cache/sass/2498a587ac2ba03461be3ee8400e5f6f322397d7/screen.scssc",
    "tmp/cache/sass/3bb5c04fe20086b066b961ec72ddea846ed0814a/_grid-background.scssc",
    "tmp/cache/sass/418bab7074745aafc7cd95603fa9954562a5db3e/_comments.css.scssc",
    "tmp/cache/sass/418bab7074745aafc7cd95603fa9954562a5db3e/_date_picker.css.scssc",
    "tmp/cache/sass/418bab7074745aafc7cd95603fa9954562a5db3e/_flash_messages.css.scssc",
    "tmp/cache/sass/418bab7074745aafc7cd95603fa9954562a5db3e/_tables.css.scssc",
    "tmp/cache/sass/4b340630174f543aee08058b2ba7d71d965fe258/_blueprint.scssc",
    "tmp/cache/sass/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_clearfix.scssc",
    "tmp/cache/sass/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_float.scssc",
    "tmp/cache/sass/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_hacks.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_colors.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_debug.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_form.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_grid.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_ie.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_interaction.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_print.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_reset.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_scaffolding.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_typography.scssc",
    "tmp/cache/sass/683b00c232502f398a2a3825bf5eb096aee2ee89/_utilities.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_all.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_buttons.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_gradients.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_icons.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_reset.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_rounded.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_sections.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_shadows.css.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_utilities.scssc",
    "tmp/cache/sass/9f11818459dbab4a771493ce0f545f6984530571/_variables.css.scssc",
    "tmp/cache/sass/a753e4e2ac7be99864eb2c1c8892da1f137e3440/_nowrap.scssc",
    "tmp/cache/sass/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_background-size.scssc",
    "tmp/cache/sass/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_images.scssc",
    "tmp/cache/sass/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_shared.scssc",
    "tmp/cache/sass/ba907ee1c957b35d8e941ffd4ed013c7557b866a/_base.css.scssc",
    "tmp/cache/sass/ba907ee1c957b35d8e941ffd4ed013c7557b866a/_forms.css.scssc",
    "tmp/cache/sass/ba907ee1c957b35d8e941ffd4ed013c7557b866a/_header.css.scssc",
    "tmp/cache/sass/ba907ee1c957b35d8e941ffd4ed013c7557b866a/_mixins.css.scssc",
    "tmp/cache/sass/ba907ee1c957b35d8e941ffd4ed013c7557b866a/_typography.css.scssc",
    "tmp/cache/sass/cd8a54404b95ecc66a330284acf22676a8113ef5/_link-colors.scssc",
    "tmp/cache/sass/ebd7cc544756782fe27f1afc24e3dc71e52a0b37/active_admin.css.scssc",
    "tmp/cache/sass/fe9cdc05e28d46e546d80709e57a9292bb29c19c/_utilities.scssc",
    "tmp/pids/server.pid",
    "tmp/sass-cache/188be3e3143469cbf426948260ad05c1d826db72/_support.scssc",
    "tmp/sass-cache/3bb5c04fe20086b066b961ec72ddea846ed0814a/_grid-background.scssc",
    "tmp/sass-cache/4b340630174f543aee08058b2ba7d71d965fe258/_blueprint.scssc",
    "tmp/sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_clearfix.scssc",
    "tmp/sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_float.scssc",
    "tmp/sass-cache/54ea6564a8e490dcb2bee49f0016bd48da5a95ec/_hacks.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_colors.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_debug.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_form.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_grid.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_ie.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_interaction.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_print.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_reset.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_scaffolding.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_typography.scssc",
    "tmp/sass-cache/683b00c232502f398a2a3825bf5eb096aee2ee89/_utilities.scssc",
    "tmp/sass-cache/7c29d2cf0996bd70eeb1fe5b1269d99cb4616b1b/active_admin.css.scssc",
    "tmp/sass-cache/7c29d2cf0996bd70eeb1fe5b1269d99cb4616b1b/ie.scssc",
    "tmp/sass-cache/7c29d2cf0996bd70eeb1fe5b1269d99cb4616b1b/print.scssc",
    "tmp/sass-cache/7c29d2cf0996bd70eeb1fe5b1269d99cb4616b1b/screen.scssc",
    "tmp/sass-cache/7c29d2cf0996bd70eeb1fe5b1269d99cb4616b1b/tour_data.css.scssc",
    "tmp/sass-cache/a753e4e2ac7be99864eb2c1c8892da1f137e3440/_nowrap.scssc",
    "tmp/sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_background-size.scssc",
    "tmp/sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_images.scssc",
    "tmp/sass-cache/ac91a4ab8048b343c11b506b64f18e037bf8c9ab/_shared.scssc",
    "tmp/sass-cache/cd8a54404b95ecc66a330284acf22676a8113ef5/_link-colors.scssc",
    "tmp/sass-cache/e39c4be0339a44e160d0abb1c9041c10d9c0ff15/_base.scssc",
    "tmp/sass-cache/fe9cdc05e28d46e546d80709e57a9292bb29c19c/_utilities.scssc"
  ]
  s.homepage = "http://github.com/mafolz/page_manager"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "simple as posible cms"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.1.1"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0"])
      s.add_runtime_dependency(%q<activeadmin>, [">= 0"])
      s.add_runtime_dependency(%q<meta_search>, [">= 0"])
      s.add_runtime_dependency(%q<compass>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, ["~> 3.1.4"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rails-i18n>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-cowboy>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<libnotify>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-test>, [">= 0"])
      s.add_development_dependency(%q<guard-bundler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.1.1"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<activeadmin>, [">= 0"])
      s.add_dependency(%q<meta_search>, [">= 0"])
      s.add_dependency(%q<compass>, [">= 0"])
      s.add_dependency(%q<sass-rails>, ["~> 3.1.4"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rails-i18n>, [">= 0"])
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<capistrano-cowboy>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<libnotify>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-test>, [">= 0"])
      s.add_dependency(%q<guard-bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.1.1"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<activeadmin>, [">= 0"])
    s.add_dependency(%q<meta_search>, [">= 0"])
    s.add_dependency(%q<compass>, [">= 0"])
    s.add_dependency(%q<sass-rails>, ["~> 3.1.4"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rails-i18n>, [">= 0"])
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<capistrano-cowboy>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<libnotify>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-test>, [">= 0"])
    s.add_dependency(%q<guard-bundler>, [">= 0"])
  end
end

